<a href="https://colab.research.google.com/github/allenphos/ML-course/blob/main/Copy_of_HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np
matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])
vector = np.random.rand(10)
display(matrix, vector)
matrix.shape, vector.shape

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

array([0.49612213, 0.42588261, 0.52604755, 0.43415726, 0.64590643,
       0.11197701, 0.5162557 , 0.59292453, 0.12004943, 0.43073021])

((3, 3), (10,))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [2]:
vector = np.round(vector + 10, 2)
matrix = matrix * 2
vector_square = vector ** 2

print("Новий vector:", vector, sep="\n")
print("Множення matrix на 2:", matrix, sep="\n")
print("вектор квадратів vector_square:", vector_square, sep="\n")

Новий vector:
[10.5  10.43 10.53 10.43 10.65 10.11 10.52 10.59 10.12 10.43]
Множення matrix на 2:
[[22 28 34]
 [40 46 52]
 [58 64 70]]
вектор квадратів vector_square:
[110.25   108.7849 110.8809 108.7849 113.4225 102.2121 110.6704 112.1481
 102.4144 108.7849]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [3]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [4]:
result_matrix = np.dot(B, A)
display(result_matrix)

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

Можна отримати 2х2 матрицю, тільки якщо B помножити на A, бо mxn * nxp = mxp

In [5]:
matrix_C = np.dot(result_matrix, C)
matrix_C

array([[0.5202],
       [0.2846]])

Якцо помножити матрицю розмірністю 2x2 на вектор 2x1, то вийде 2х1

In [6]:
matrix_D = np.dot(result_matrix, D)
matrix_D

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])

D матриця перестановки тому стовпці переставлені місцями


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [7]:
t_result_matrix = result_matrix.T
t_vector = vector.T

print("Транспонування result_matrix:", t_result_matrix, t_result_matrix.shape, sep="\n")
print("Транспонування vector:", t_vector, t_vector.shape, sep="\n")

Транспонування result_matrix:
[[0.7281 0.2034]
 [0.5202 0.2846]]
(2, 2)
Транспонування vector:
[10.5  10.43 10.53 10.43 10.65 10.11 10.52 10.59 10.12 10.43]
(10,)


Одномірний вектор не змінює форму під час транспонування

In [8]:
column_vector = np.expand_dims(vector, axis=1)

print("column_vector:", column_vector, column_vector.shape, sep="\n")
print("vector:", vector, vector.shape, sep="\n")

column_vector:
[[10.5 ]
 [10.43]
 [10.53]
 [10.43]
 [10.65]
 [10.11]
 [10.52]
 [10.59]
 [10.12]
 [10.43]]
(10, 1)
vector:
[10.5  10.43 10.53 10.43 10.65 10.11 10.52 10.59 10.12 10.43]
(10,)


expand_dims додає новий вимір до вектора, перетворюючи його в стовпець з формою 10х1

In [18]:
# Порівняння норм векторів
norm1 = np.linalg.norm(vector)
norm2 = np.linalg.norm(column_vector)
print("Норма вектора 1:", norm1)
print("Норма вектора 2:", norm2)
print("Чи вектори мають однакову норму:", norm1 == norm2)

Норма вектора 1: 32.99019702881448
Норма вектора 2: 32.99019702881448
Вектори мають однакову норму: True


In [9]:
t_column_vector = column_vector.T

print("Транспонований вектор column_vector:", t_column_vector, t_column_vector.shape, sep="\n")

Транспонований вектор column_vector:
[[10.5  10.43 10.53 10.43 10.65 10.11 10.52 10.59 10.12 10.43]]
(1, 10)


In [23]:
# Порівняння норм векторів
norm1 = np.linalg.norm(vector)
norm2 = np.linalg.norm(t_column_vector)
print("Норма вектора 1:", norm1)
print("Норма вектора 2:", norm2)
print("Чи вектори мають однакову норму:", norm1 == norm2)

Норма вектора 1: 32.99019702881448
Норма вектора 2: 32.99019702881448
Вектори мають однакову норму: True
